### ISSUE TITLE
Duplicating File

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#31]
- Your Files Modal
- Right-click, duplicate
- File doesn't duplicate, error in console

![image 2018-10-26 at 2 42 25 pm](https://user-images.githubusercontent.com/1817068/47593762-708f5f00-d92d-11e8-9c3d-4a5541da2020.png)

**Comment by luigi-rosso** [comment]
This is fixed now, but I noticed the "Copying" animation doesn't spin.

**Comment by neurowave** [comment]
I'm getting an error still. Modal was opened in Flare.

![image 2018-11-10 at 7 54 16 pm](https://user-images.githubusercontent.com/1817068/48308904-8d798400-e522-11e8-964b-3bb04bd22776.png)

**Comment by neurowave** [comment]
I fixed the copying animation, btw. I'm still getting a bug (see above) and I think we should probably disable being able to select and right click when it's still copying:

![image 2018-11-10 at 7 59 21 pm](https://user-images.githubusercontent.com/1817068/48308938-5061c180-e523-11e8-98bc-dea870e9eced.png)
